Overview Updates
RFP2305-Team-Mercury/frontendcapstone pull request #37
Opened 2023-07-05 19:33 UTC by carolinerobbins

- Added zoom image (still needs tweaking on positioning)
- Moved details into state for optimization
- Added tests to achieve 70% coverage
- Fixed merge error in App.js
- Fixed details reducer error (forgot to import action)

2023-07-05 22:57 UTC, pdaly91 commented on src/components/App.jsx
I noticed you removed answer on line 20 and added back the button on line 34. Is that correct? Wanted to double check first

2023-07-05 23:49 UTC, carolinerobbins commented on src/components/App.jsx
Oops I did not merge that correctly - I meant to combine!

2023-07-06 03:39 UTC, pdaly91 requested changes

2023-07-06 03:39 UTC, pdaly91 commented on src/components/overview/Gallery.jsx
You have some duplicated lines in here, could you please check?

2023-07-06 03:39 UTC, pdaly91 commented on src/components/App.jsx
You have some duplicated lines in here

2023-07-06 03:39 UTC, pdaly91 commented on src/components/overview/Styles.jsx
Duplicate lines

2023-07-06 03:39 UTC, pdaly91 commented on src/components/relatedProducts/ComparisonModal.jsx
Maybe some duplicates here too?

2023-07-06 05:06 UTC, ahusu approved these changes
Looks good overall, I think you gotta check out Patrick's concerns first though

2023-07-06 15:36 UTC, carolinerobbins commented on src/components/overview/Details.jsx
> -      <div className="flex-2 w-2/3 mt-4 border-r-2 border-black">
Yes, I needed to separate it so the slogan/description show under the gallery!

2023-07-06 15:40 UTC, carolinerobbins commented on src/components/App.jsx
resolved!

2023-07-06 15:42 UTC, carolinerobbins commented on src/components/overview/Gallery.jsx
resolved!

2023-07-06 16:25 UTC, pdaly91 approved these changes
Thanks for fixing those things!

2023-07-06 16:25 UTC, merged